---
- name: Install fonts
  tags:
    - desktop
  vars:
    base_desktop_segoe_path: "{{ vault_home }}/src/github/system-repos/segoe-ui-linux"
    base_desktop_fonts_path: "{{ vault_home }}/.fonts"
  block:
    - name: Install fonts (Ubuntu)
      ansible.builtin.package:
        name:
          - ttf-mscorefonts-installer
      when: ansible_distribution == "Ubuntu"
      become: true

    - name: Download Segoe Fonts
      ansible.builtin.git:
        repo: https://github.com/mrbvrz/segoe-ui-linux.git
        dest: "{{ base_desktop_segoe_path }}"

    - name: Create .fonts directory
      ansible.builtin.file:
        path: "{{ base_desktop_fonts_path }}"
        state: directory
        mode: "0750"

    - name: Copy Segoe Fonts
      ansible.builtin.command: rsync -av -exclude=".*" . {{ base_desktop_fonts_path }}
      args:
        chdir: "{{ base_desktop_segoe_path }}/font"

    - name: Flush font cache
      ansible.builtin.command: fc-cache -fv

  # sudo rpm -i https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
