---
- name: Install bluetooth
  tags:
    - apps
  block:
    - name: Check if Bluetooth Hardware Exists
      ansible.builtin.shell: lsusb | grep Bluetooth | wc --lines
      register: base_desktop_bluetooth_hardware_count
      ignore_errors: true

    - name: Install Bluetooth
      ansible.builtin.package:
        name:
          - bluez
          - bluez-tools
          - blueman
      when: (base_desktop_bluetooth_hardware_count.stdout|int) > 0
      become: true
