---
- name: Install Alacritty
  become: true
  tags:
    - apps
  vars:
    base_desktop_ubuntu_key: /etc/apt/keyrings/alacritty.asc
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Download Alacritty GPG Key
      ansible.builtin.get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3a160895cc2ce253085d08a552b24df7d43b5377
        dest: "{{ base_desktop_ubuntu_key }}"
        mode: "0644"

    - name: Add Alacritty Repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by={{ base_desktop_ubuntu_key }}] https://ppa.launchpadcontent.net/aslatter/ppa/ubuntu/ {{ ansible_distribution_release }} main
        state: present
        filename: alacritty

    - name: Install Alacritty
      ansible.builtin.package:
        name: alacritty
