---
- name: Install Xmenu
  tags:
    - desktop
  vars:
    desktop_xmenu_path: "{{ vault_home }}/src/github/system-repos/xmenu"
  block:
    - name: Install xmenu dependencies (Ubuntu)
      ansible.builtin.package:
        name:
          - libx11-dev
          - libxft-dev
          - make
          # original
          - libxinerama-dev
          - libimlib2-dev
      when: ansible_distribution == "Ubuntu"
      become: true

    - name: Clone xmenu
      ansible.builtin.git:
        repo: https://github.com/phillbush/xmenu.git
        dest: "{{ desktop_xmenu_path }}"
        version: "9c6188e6f41176909fea4b8d8d408597a29cd3e0" # Last working commit before stopped working with polybar

    - name: Run xmenu - make
      ansible.builtin.command: make
      args:
        chdir: "{{ desktop_xmenu_path }}"

    - name: Run xmenu - make install
      ansible.builtin.command: make install
      args:
        chdir: "{{ desktop_xmenu_path }}"
      become: true
