---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${DISTRO:-ubuntu2204}
    image: geerlingguy/docker-${DISTRO:-ubuntu2204}-ansible:latest
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
