- name: Install dunst
  tags:
    - desktop
  block:
    - name: Install dunst dependencies (Ubuntu)
      ansible.builtin.package:
        name:
          - libdbus-1-dev
          - libx11-dev
          - libxinerama-dev
          - libxrandr-dev
          - libxss-dev
          - libglib2.0-dev
          - libpango1.0-dev
          - libgtk-3-dev
          - libxdg-basedir-dev
      when: ansible_distribution == "Ubuntu"
      become: true

    - name: Clone dunst
      ansible.builtin.git:
        repo: https://github.com/dunst-project/dunst.git
        dest: $HOME/src/github/system-repos/dunst

    - name: Make dunst build directory
      ansible.builtin.file:
        path: $HOME/src/github/system-repos/dunst/build
        state: directory
        mode: 0755

    - name: Run dunst - make
      ansible.builtin.command: make WAYLAND=0 SYSTEMD=0 SYSCONFDIR=/etc/xdg
      args:
        chdir: $HOME/src/github/system-repos/dunst

    - name: Run dunst - make install
      ansible.builtin.command: make WAYLAND=0 SYSTEMD=0 SYSCONFDIR=/etc/xdg install
      args:
        chdir: "{{ lookup('env', 'HOME') }}/src/github/system-repos/dunst"
      become: true
