- name: Install Waybar
  become: true
  tags:
    - desktop
  block:
    - name: Install waybar build dependencies (Ubuntu)
      ansible.builtin.package:
        name:
          - cmake
          - meson
          - scdoc
          - wayland-protocols
      when: ansible_distribution == "Ubuntu"

    - name: Install waybar required dependencies (Ubuntu)
      ansible.builtin.package:
        name:
          - clang-tidy
          - gobject-introspection
          - libdbusmenu-gtk3-dev
          - libevdev-dev
          - libfmt-dev
          - libgirepository1.0-dev
          - libgtk-3-dev
          - libgtkmm-3.0-dev
          - libinput-dev
          - libjsoncpp-dev
          - libmpdclient-dev
          - libnl-3-dev
          - libnl-genl-3-dev
          - libpulse-dev
          - libsigc++-2.0-dev
          - libspdlog-dev
          - libwayland-dev
          - scdoc
          - upower
          - libxkbregistry-dev
      when: ansible_distribution == "Ubuntu"

- name: Clone waybar Repository
  tags:
    - desktop
  block:
    - name: Clone waybar Repository
      ansible.builtin.git:
        repo: https://github.com/alexays/waybar.git
        dest: $HOME/src/github/system-repos/waybar
        recursive: true

    - name: Run waybar - meson build
      ansible.builtin.command: meson build
      args:
        chdir: $HOME/src/github/system-repos/waybar

    - name: Run waybar - ninja build
      ansible.builtin.command: ninja -C build
      args:
        chdir: $HOME/src/github/system-repos/waybar

    - name: Run waybar
      ansible.builtin.command: ./build/waybar
      args:
        chdir: $HOME/src/github/system-repos/waybar

- name: Run waybar Install
  become: true
  tags:
    - desktop
  block:
    - name: Run waybar install
      ansible.builtin.command: ninja -C build install
      args:
        chdir: "{{ lookup('env', 'HOME') }}/src/github/system-repos/waybar/build"
