- name: Install sway
  tags:
    - desktop
  block:
    - name: Install i3 build tools
      ansible.builtin.package:
        name:
          - gcc
          - make
          - meson
      become: true

    - name: Install i3 dependency libraries (Ubuntu)
      ansible.builtin.package:
        name:
          - libxcb1-dev
          - libxcb-keysyms1-dev
          - libpango1.0-dev
          - libxcb-util0-dev
          - libxcb-icccm4-dev
          - libyajl-dev
          - libstartup-notification0-dev
          - libxcb-randr0-dev
          - libev-dev
          - libxcb-cursor-dev
          - libxcb-xinerama0-dev
          - libxcb-xkb-dev
          - libxkbcommon-dev
          - libxkbcommon-x11-dev
          - autoconf
          - libxcb-xrm0
          - libxcb-xrm-dev
          - automake
          - libxcb-shape0-dev
      when: ansible_distribution == "Ubuntu"
      become: true

    - name: Install i3 dependency libraries (Fedora)
      ansible.builtin.package:
        name:
          - libxcb-devel
          - xcb-util-keysyms-devel
          - xcb-util-devel
          - xcb-util-wm-devel
          - xcb-util-xrm-devel
          - yajl-devel
          - libXrandr-devel
          - startup-notification-devel
          - libev-devel
          - xcb-util-cursor-devel
          - libXinerama-devel
          - libxkbcommon-devel
          - libxkbcommon-x11-devel
          - pcre-devel
          - pango-devel
          - gcc
          - automake
          - perl-devel
      when: ansible_distribution == "Fedora"
      become: true

    - name: Clone i3 from github
      ansible.builtin.git:
        repo: https://www.github.com/Airblader/i3.git
        dest: $HOME/src/github/system-repos/i3-gaps
        clone: true
        update: true

    - name: Make i3 build directory
      ansible.builtin.file:
        path: $HOME/src/github/system-repos/i3-gaps/build
        state: directory
        mode: 0755

    - name: Run i3 - meson
      ansible.builtin.command: meson ..
      args:
        chdir: $HOME/src/github/system-repos/i3-gaps/build

    - name: Run i3 - ninja
      ansible.builtin.command: ninja
      args:
        chdir: $HOME/src/github/system-repos/i3-gaps/build

    - name: Run i3 - ninja install
      ansible.builtin.command: ninja install
      args:
        chdir: "{{ lookup('env', 'HOME') }}/src/github/system-repos/i3-gaps/build"
      become: true
