- name: Install rofi
  tags:
    - desktop
  block:
    - name: Install rofi dependencies
      ansible.builtin.package:
        name:
          - bison
          - flex
      become: true

    - name: Clone rofi
      ansible.builtin.git:
        repo: https://github.com/davatorium/rofi.git
        dest: $HOME/src/github/system-repos/rofi
        recursive: true

    - name: Make rofi build directory
      ansible.builtin.file:
        path: $HOME/src/github/system-repos/rofi/build
        state: directory
        mode: 0755

    - name: Run rofi - autoreconf
      ansible.builtin.command: autoreconf -i
      args:
        chdir: $HOME/src/github/system-repos/rofi

    - name: Run rofi - configure
      ansible.builtin.command: ../configure --disable-check
      args:
        chdir: $HOME/src/github/system-repos/rofi/build

    - name: Run rofi - make
      ansible.builtin.command: make
      args:
        chdir: $HOME/src/github/system-repos/rofi/build

    - name: Run rofi - make install
      ansible.builtin.command: make install
      args:
        chdir: "{{ lookup('env', 'HOME') }}/src/github/system-repos/rofi/build"
      become: true
