---
- name: Install rofi
  tags:
    - desktop
    - xorg
  vars:
    desktop_rofi_path: '{{ vault_home }}/src/github/system-repos/rofi'
  block:
    - name: Install rofi dependencies
      ansible.builtin.package:
        name:
          - autoconf
          - libglib2.0-dev
          - libxkbcommon-dev
          - libxkbcommon-x11-dev
          - libxcb-util-dev
          - libxcb-ewmh-dev
          - libxcb-icccm4-dev
          - libxcb-cursor-dev
          - libxcb-randr0-dev
          - libxcb-xinerama0-dev
          - libpango1.0-dev
          - libpangocairo-1.0-0
          - libstartup-notification0-dev
          - libgdk-pixbuf-2.0-dev
          - make
          # previous
          - bison
          - flex
      become: true

    - name: Clone rofi
      ansible.builtin.git:
        repo: https://github.com/davatorium/rofi.git
        dest: '{{ desktop_rofi_path }}'
        #version: 'e563cd3ad0795cf4f3e5698588e2387e3373b512'
        #refspec: +refs/pull/*:refs/heads/*
        recursive: true

    - name: Make rofi build directory
      ansible.builtin.file:
        path: '{{ desktop_rofi_path }}/build'
        state: directory
        mode: '0755'

    - name: Run rofi - autoreconf
      ansible.builtin.command: autoreconf -i
      args:
        chdir: '{{ desktop_rofi_path }}'

    - name: Run rofi - configure
      ansible.builtin.command: ../configure --disable-check
      args:
        chdir: '{{ desktop_rofi_path }}/build'

    - name: Run rofi - make
      ansible.builtin.command: make
      args:
        chdir: '{{ desktop_rofi_path }}/build'

    - name: Run rofi - make install
      ansible.builtin.command: make install
      args:
        chdir: '{{ desktop_rofi_path }}/build'
      become: true
