- name: Install bat
  tags:
    - apps
  vars:
    home: '{{ vault_home }}'
  block:
    - name: Install bat
      ansible.builtin.package:
        name: bat
      become: true

    - name: 'Make sure ~/.local/bin exists'
      ansible.builtin.file:
        path: '{{ home }}/.local/bin'
        state: directory
        mode: '0755'

    - name: Set up user icon
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: '{{ home }}/.local/bin/bat'
        state: link
      when: ansible_distribution == "Ubuntu"
