- name: Install bat
  tags:
    - apps
  block:
    - name: Install bat
      ansible.builtin.package:
        name: bat
      become: true

    - name: Make sure $HOME/.local/bin exists
      ansible.builtin.file:
        path: $HOME/.local/bin
        state: directory
        mode: '0755'

    - name: Set up user icon
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: $HOME/.local/bin/bat
        state: link
      when: ansible_distribution == "Ubuntu"
