- name: Remove Snapd
  become: true
  tags:
    - system
  block:
    - name: Remove snapd
      ansible.builtin.apt:
        name: snapd
        state: absent
        purge: true
      when: ansible_distribution == "Ubuntu"

    - name: Remove snapd-related directories
      ansible.builtin.file:
        path: '{{ snap_folder }}'
        state: absent
      loop:
        - /snap
        - /var/snap
        - /var/lib/snapd
        - $HOME/snap # root
        - "{{ lookup('env', 'HOME') }}/snap" # nonroot
      loop_control:
        loop_var: snap_folder
      when: ansible_distribution == "Ubuntu"
      tags: molecule-idempotence-notest

    - name: Hold snapd from install
      ansible.builtin.dpkg_selections:
        name: snapd
        selection: hold
      when: ansible_distribution == "Ubuntu"
      tags: molecule-idempotence-notest
