- block:
  - name: Add solaar ppa 
    ansible.builtin.apt_repository:
      repo: ppa:solaar-unifying/stable

  - name: Install solaar
    ansible.builtin.package:
      name:
        - solaar
  become: true