- block:
  - name: Update apt cache
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: Install base tools
    ansible.builtin.package:
      name: 
        - exa
        - git
        - vim
        - firefox
        - rsync
        - acl

  - name: Install base tools
    ansible.builtin.package:
      name: 
        - network-manager
        - apt-utils
    when: ansible_distribution == "Ubuntu"
  become: true
