- block:
  - name: Install other apps
    ansible.builtin.package:
      name:
        - darktable
        - fd-find
        - gimp
        - htop
        - keepassxc
        - libreoffice
        - lxappearance
        - meld
        - mesa-utils  #for glxinfo
        - neofetch
        - newsboat
        - nfs-common
        - policykit-1-gnome
        - qt5ct
        - thunar
        - tmux
        - ttf-mscorefonts-installer
        - unzip
        - xdotool
        - xsel
        - youtube-dl
        - zathura
        - zip
  become: true    
