- block:
  - name: Install Audio tools
    ansible.builtin.package:
      name:
        - pavucontrol
        - alsa-utils
        
  - name: Add to Audio group
    user:
      name: "{{ ansible_user_id }}"
      groups: audio
      state: present
      append: yes
  become: true