- block:
  - name: Install polybar build dependencies
    ansible.builtin.package:
      name:
        - build-essential
        - git
        - cmake
        - cmake-data
        - pkg-config
        - python3
        - python3-sphinx
        - python3-packaging
      
  - name: Install polybar required dependencies
    ansible.builtin.package:
      name:
        - libuv1-dev 
        - libcairo2-dev 
        - libxcb1-dev 
        - libxcb-util0-dev 
        - libxcb-randr0-dev 
        - libxcb-composite0-dev 
        - python3-xcbgen 
        - xcb-proto 
        - libxcb-image0-dev 
        - libxcb-ewmh-dev 
        - libxcb-icccm4-dev

  - name: Install polybar optional dependencies
    ansible.builtin.package:
      name:
        - libxcb-xkb-dev
        - libxcb-xrm-dev
        - libxcb-cursor-dev
        - libasound2-dev
        - libpulse-dev
        - i3-wm
        - libjsoncpp-dev
        - libmpdclient-dev
        - libcurl4-openssl-dev
        - libnl-genl-3-dev
  become: true
        
- block:
  - name: Clone Polybar Repository
    ansible.builtin.git:
      repo: https://github.com/polybar/polybar.git
      dest: $HOME/src/github/system-repos/polybar
      recursive: yes

  - name: Make polybar build directory
    ansible.builtin.file:
      path: $HOME/src/github/system-repos/polybar/build 
      state: directory
      mode: 0755

  - name: Run polybar - cmake
    ansible.builtin.command: cmake ..
    args:
      chdir: $HOME/src/github/system-repos/polybar/build

  - name: Run polybar - make
    ansible.builtin.shell: make -j$(nproc)
    args:
      chdir: $HOME/src/github/system-repos/polybar/build

- block:
  - name: Run polybar - make install 
    ansible.builtin.command: make install
    args:
      chdir: $HOME/src/github/system-repos/polybar/build
  become: true