- block:
  - name: Install xmenu dependencies
    ansible.builtin.package:
      name:
        - libxinerama-dev
        - libimlib2-dev
    become: true

  - name: Clone xmenu
    ansible.builtin.git:
      repo: https://github.com/phillbush/xmenu.git
      dest: $HOME/src/github/system-repos/xmenu

  - name: Run xmenu - make
    ansible.builtin.command: make
    args:
      chdir: $HOME/src/github/system-repos/xmenu

  - name: Run xmenu - make install
    ansible.builtin.command: make install
    args:
      chdir: "{{ lookup('env', 'HOME') }}/src/github/system-repos/xmenu"
    become: true