---
- name: Install SDDM
  tags:
    - desktop
  vars:
    desktop_i3wm_sddmchili_path: "{{ vault_home }}/src/github/system-repos/sddm-chili"
  block:
    - name: Install sddm
      ansible.builtin.package:
        name: sddm
      become: true

    - name: Generate default SDDM config file
      ansible.builtin.shell: sddm --example-config | tee /etc/sddm.conf
      become: true

    - name: Clone Chili SDDM Theme
      ansible.builtin.git:
        repo: https://github.com/MarianArlt/sddm-chili.git
        dest: "{{ desktop_i3wm_sddmchili_path }}"

    - name: Create chili theme directory
      ansible.builtin.file:
        path: /usr/share/sddm/themes/chili
        state: directory
        mode: "0755"
      become: true

    - name: Copy chili theme to sddm themes folder
      ansible.posix.synchronize:
        src: "{{ desktop_i3wm_sddmchili_path }}"
        dest: /usr/share/sddm/themes/chili
      become: true

    - name: Install chili theme dependencies
      ansible.builtin.package:
        name:
          - qml-module-qtquick-controls
          - qml-module-qtquick-controls2
      when: ansible_distribution == "Ubuntu"
      become: true

    - name: Set SDDM theme
      ansible.builtin.shell: sed -i 's/^Current=[a-zA-Z0-9-]*$/Current=chili/g' /etc/sddm.conf
      become: true

    - name: Set up user icon
      ansible.builtin.file:
        src: "{{ vault_home }}/.face"
        dest: "{{ vault_home }}/.face.icon"
        state: link

    - name: Give sddm user access to user's home directory
      ansible.posix.acl:
        path: "{{ vault_home }}"
        entity: sddm
        etype: user
        permissions: x
        state: present
      become: true

    - name: Give sddm user access to ~/.face.icon
      ansible.posix.acl:
        path: "{{ vault_home }}/.face.icon"
        entity: sddm
        etype: user
        permissions: r
        state: present
      become: true
