---
- name: Install i3 apps
  become: true
  tags:
    - apps
    - desktop
  block:
    - name: Install apps used by i3
      ansible.builtin.package:
        name:
          - feh
          - flameshot
          - thunar
          - wmctrl
          - zenity
