- name: Install dunst
  tags:
    - desktop
  vars:
    desktop_i3wm_dunst_path: '{{ vault_home }}/src/github/system-repos/dunst'
  block:
    - name: Install dunst dependencies (Ubuntu)
      ansible.builtin.package:
        name:
          - libdbus-1-dev
          - libglib2.0-dev
          - libgtk2.0-dev
          - libnotify-dev
          - libpango1.0-dev
          - libx11-dev
          - libxdg-basedir-dev
          - libxinerama-dev
          - libxrandr-dev
          - libxss-dev
      when: ansible_distribution == "Ubuntu"
      become: true

    - name: Install dunst dependencies (Fedora)
      ansible.builtin.package:
        name:
          - dbus-devel
          - libX11-devel
          - libXrandr-devel
          - glib2-devel
          - pango-devel
          - gtk3-devel
          - libxdg-basedir-devel
          - libXScrnSaver-devel
          - libnotify-devel
      when: ansible_distribution == "Fedora"
      become: true

    - name: Clone dunst
      ansible.builtin.git:
        repo: https://github.com/dunst-project/dunst.git
        dest: '{{ desktop_i3wm_dunst_path }}'

    - name: Make dunst build directory
      ansible.builtin.file:
        path: '{{ desktop_i3wm_dunst_path }}/build'
        state: directory
        mode: '0755'

    - name: Run dunst - make
      ansible.builtin.command: make WAYLAND=0 SYSTEMD=0 SYSCONFDIR=/etc/xdg
      args:
        chdir: '{{ desktop_i3wm_dunst_path }}'

    - name: Run dunst - make install
      ansible.builtin.command: make WAYLAND=0 SYSTEMD=0 SYSCONFDIR=/etc/xdg install
      args:
        chdir: '{{ desktop_i3wm_dunst_path }}'
      become: true
