---
- name: Converge
  hosts: all
  tasks:
    - name: Role - docker
      include_role:
        name: ../../roles/docker

    - name: Role - docker-rootless
      include_role:
        name: ../../roles/docker-rootless
