---
- name: Install SDDM
  tags:
    - desktop
  block:
    - name: Install sddm
      ansible.builtin.package:
        name: sddm
      become: true

    - name: Generate default SDDM config file
      ansible.builtin.shell: sddm --example-config | tee /etc/sddm.conf
      become: true
