---
- name: Install SDDM Chili Theme
  tags:
    - desktop
  vars:
    desktop_sddmchili_path: "{{ vault_home }}/src/github/system-repos/sddm-chili"
  block:
    - name: Clone Chili SDDM Theme
      ansible.builtin.git:
        repo: https://github.com/MarianArlt/sddm-chili.git
        dest: "{{ desktop_sddmchili_path }}"

    - name: Create chili theme directory
      ansible.builtin.file:
        path: /usr/share/sddm/themes/chili
        state: directory
        mode: "0755"
      become: true

    - name: Copy chili theme to sddm themes folder
      ansible.builtin.copy:
        src: "{{ desktop_sddmchili_path }}/"
        dest: /usr/share/sddm/themes/chili
        mode: "0755"
        remote_src: true
      become: true

    - name: Install chili theme dependencies
      ansible.builtin.package:
        name:
          - qml-module-qtquick-controls
          - qml-module-qtquick-controls2
      when: ansible_distribution == "Ubuntu"
      become: true

    - name: Set SDDM theme
      ansible.builtin.shell: sed -i 's/^Current=[a-zA-Z0-9-]*$/Current=chili/g' /etc/sddm.conf
      become: true
