---
- name: Install NodeJS
  vars:
    nvm_version: v0.39.7
    nvm_file: /tmp/nvm_install.sh
  tags:
    - dev
  block:
    - name: Download NVM Install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh
        dest: "{{ nvm_file }}"
        mode: "0755"
      when: ansible_distribution == "Ubuntu"

    - name: Install NVM
      ansible.builtin.shell:
        cmd: PROFILE=/dev/null {{ nvm_file }}

    - name: Source .bashrc 
      ansible.builtin.shell:
        cmd: source ~/.bashrc

    - name: Install Nodejs
      ansible.builtin.shell:
        cmd: nvm install node
