- block:
  - name: Set NTP to use the local NTP server
    copy:
      src: ../templates/timesyncd.conf.j2
      dest: /etc/systemd/timesyncd.conf
      owner: root
      group: root

  - name: Restart NTP service
    service:
      name: systemd-timesyncd
      state: restarted
  become: true
  tags:
  - system
