- name: Set NTP Server
  become: true
  tags:
    - system
  block:
    - name: Set NTP to use the local NTP server
      ansible.builtin.copy:
        src: ../templates/timesyncd.conf.j2
        dest: /etc/systemd/timesyncd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Install timesyncd
      ansible.builtin.apt:
        update-cache: true
        state: present
        name: systemd-timesyncd

    - name: Restart NTP service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: systemd-timesyncd.service
      tags: molecule-idempotence-notest

    # - name: Restart NTP service
    #   ansible.builtin.service:
    #     name: systemd-timesyncd
    #     state: restarted
