- name: Set motd
  become: true
  tags:
    - system
  block:
    - name: Collect files in motd directory
      ansible.builtin.find:
        paths: '/etc/update-motd.d'
        hidden: true
        recurse: true
        file_type: any
      register: collected_files

    - name: Remove collected files
      ansible.builtin.file:
        path: '{{ file_to_remove.path }}'
        state: absent
      with_items: '{{ collected_files.files }}'
      loop_control:
        loop_var: file_to_remove

    - name: Copy motd
      ansible.builtin.copy:
        src: ../templates/01-custom.j2
        dest: /etc/update-motd.d/01-custom
        owner: root
        group: root
        mode: '0755'
