---
- name: Install Wayland
  become: true
  tags:
    - desktop
  block:
    - name: Install Wayland (Ubuntu)
      ansible.builtin.package:
        name:
          - wayland-protocols
      when: ansible_distribution == "Ubuntu"
