---
- name: Converge
  hosts: all
  vars_files: ../../vars/vault.test.yml
  pre_tasks:
    - name: Role - add user
      include_role:
        name: ../../roles/add_users

    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - name: Role - applications
      include_role:
        name: ../../roles/applications
