---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  #yamllint .
  ansible-lint .
