- block:
  - name: Install neovim build dependencies (Ubuntu)
    ansible.builtin.package:
      name: 
        - ninja-build
        - gettext
        - libtool
        - autoconf
        - automake
        - cmake
        - unzip
        - curl
        - doxygen
        - libtool-bin
        - g++
        - pkg-config
    when: ansible_distribution == "Ubuntu"
    become: true

  - name: Install neovim build dependencies (Fedora)
    ansible.builtin.package:
      name: 
        - ninja-build
        - gettext
        - libtool
        - autoconf
        - automake
        - cmake
        - unzip
        - curl
        - patch
        - gcc
        - gcc-c++
        - make
        - pkgconfig 
    when: ansible_distribution == "Fedora"
    become: true

  - name: Clone neovim from github
    ansible.builtin.git:
      repo: https://www.github.com/neovim/neovim.git
      dest: $HOME/src/github/system-repos/neovim
      version: d367ed9b23d481998d297d812f54b950e5511c24
      refspec: '+refs/pull/*:refs/heads/*'
      clone: yes
      update: yes

  - name: Run neovim - make
    ansible.builtin.command: make CMAKE_BUILD_TYPE=Release
    args:
      chdir: $HOME/src/github/system-repos/neovim

  - name: Run neovim - make install
    ansible.builtin.command: make install
    args:
      chdir: "{{ lookup('env', 'HOME') }}/src/github/system-repos/neovim"
    become: true
  tags:
  - apps
