- name: Install fonts
  tags:
    - desktop
  block:
    - name: Install fonts (Ubuntu)
      ansible.builtin.package:
        name:
          - ttf-mscorefonts-installer
      when: ansible_distribution == "Ubuntu"

    - name: Download Segoe Fonts
      ansible.builtin.git:
        repo: https://github.com/mrbvrz/segoe-ui-linux.git
        dest: $HOME/src/github/system-repos/segoe-ui-linux

    - name: Create .fonts directory
      ansible.builtin.file:
        path: $HOME/.fonts
        state: directory
        mode: '0640'

    - name: Copy Segoe Fonts
      ansible.builtin.command: rsync -av -exclude=".*" . $HOME/.fonts
      args:
        chdir: $HOME/src/github/system-repos/segoe-ui-linux/font

    - name: Flush font cache
      ansible.builtin.command: fc-cache -fv

  # sudo rpm -i https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
