- name: Install alacritty
  become: true
  tags:
    - apps
  block:
    - name: Add alacritty ppa
      ansible.builtin.apt_repository:
        repo: ppa:aslatter/ppa
      when: ansible_distribution == "Ubuntu"

    - name: Install alacritty
      ansible.builtin.package:
        name: alacritty
