- name: Disable Wifi Adapter
  become: true
  tags:
    - hestia
  block:
    - name: Disable Wifi Adapter
      ansible.builtin.blockinfile:
        path: /etc/modprobe.d/blacklist.conf
        mode: 0644
        owner: root
        group: root
        create: true
        block: |
          # 12/12/2021 Block wifi
          blacklist iwlwifi
