- name: Disable Extra Ethernet Adapter
  become: true
  tags:
    - hestia
  block:
    - name: Disable Extra Ethernet Adapter
      ansible.builtin.file:
        path: /etc/netplan/00-installer-config.yaml
        state: touch
        mode: '0644'
      when: ansible_distribution == "Ubuntu"
# Change the renderer to NetworkManager and make enp7s0 optional
#
#     optional=true
#     dhcp4=false
#     dhcp6=false
#
# Sample
#
# network:
#   version: 2
#   renderer: NetworkManager
#   ethernets:
#     enp6s0:
#       dhcp4: true
#     enp7s0:
#       dhcp4: false
#       dhcp6: false
#       optional: true

# sudo netplan apply
