---
- name: Make Theme Folders
  tags:
    - desktop
  vars:
    desktop_i3wm_themes_dir: "{{ vault_home }}/.themes"
    desktop_i3wm_fonts_dir: "{{ vault_home }}/.fonts"
    desktop_i3wm_icons_dir: "{{ vault_home }}/.icons"
  block:
    - name: Make .themes directory
      ansible.builtin.file:
        path: "{{ desktop_i3wm_themes_dir }}"
        state: directory
        mode: "0755"

    - name: Make .fonts directory
      ansible.builtin.file:
        path: "{{ desktop_i3wm_fonts_dir }}"
        state: directory
        mode: "0755"

    - name: Make .icons directory
      ansible.builtin.file:
        path: "{{ desktop_i3wm_icons_dir }}"
        state: directory
        mode: "0755"

- name: Symlink Theme Folders
  become: true
  tags:
    - desktop
  block:
    - name: Link .themes to root
      ansible.builtin.file:
        src: "{{ desktop_i3wm_themes_dir }}"
        dest: /root/.themes
        state: link

    - name: Link .fonts to root
      ansible.builtin.file:
        src: "{{ desktop_i3wm_fonts_dir }}"
        dest: /root/.fonts
        state: link

    - name: Link .icons to root
      ansible.builtin.file:
        src: "{{ desktop_i3wm_icons_dir }}"
        dest: /root/.icons
        state: link
