- block:
  - name: Install Neovim
    ansible.builtin.apt_repository:
      repo: ppa:neovim-ppa/unstable
    when: ansible_distribution == "Ubuntu"

  - name: Enable project agriffis/neovim-nightly
    community.general.copr:
      name: agriffis/neovim-nightly
    when: ansible_distribution == "Fedora"

  - name: Install neovim
    ansible.builtin.package:
      name: neovim
  become: true