- block:
  - name: Install pass (Ubuntu)
    ansible.builtin.package:
      name:
        - pass
        - pass-extension-otp
    when: ansible_distribution == "Ubuntu"

  - name: Install pass (Fedora)
    ansible.builtin.package:
      name:
        - pass
        - pass-otp
    when: ansible_distribution == "Fedora"
      
  become: true
  tags:
  - apps

  # Configure gpg


