- block:
  - name: Install Audio tools
    ansible.builtin.package:
      name:
        - pavucontrol
        - alsa-utils

  - name: Add to Audio group
    user:
      name: "{{ lookup('env', 'USER') }}"
      groups: audio
      state: present
      append: yes
  become: true
  tags:
    - apps
    - system   