---
- name: Install Blanket
  tags:
    - apps
  vars:
    applications_blanket_path: "{{ vault_home }}/src/github/system-repos/blanket"

  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install dependencies
      ansible.builtin.package:
        name:
          - git
          - desktop-file-utils
          - python3-gi
          - python3-gi-cairo
          - gir1.2-gtk-3.0
          - libgtk-4-dev
          - libadwaita-1-0
          - libgstreamer1.0-dev
          - meson
          - ninja-build
      become: true

    - name: Clone repository
      ansible.builtin.git:
        repo: https://github.com/rafaelmardojai/blanket
        dest: "{{ applications_blanket_path }}"
        recursive: true

    - name: Run meson
      ansible.builtin.command: meson builddir --prefix=/usr/local
      args:
        chdir: "{{ applications_blanket_path }}"
        creates: "{{ applications_blanket_path }}/builddir"

    - name: Run ninja
      ansible.builtin.command: ninja -C builddir install
      args:
        chdir: "{{ applications_blanket_path }}"
        creates: /usr/local/bin/blanket
      become: true
