- name: Install Vault
  become: true
  tags:
    - apps
  vars:
    applications_ubuntu_vault_key: '/etc/apt/trusted.gpg.d/hashicorp-vault.asc'
  block:
    - name: Download Vault GPG Key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: '{{ applications_ubuntu_vault_key }}'
        mode: '0644'
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: Add Vault Repository (Ubuntu or Debian)
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by={{ applications_ubuntu_vault_key }}] https://apt.releases.hashicorp.com $(lsb_release -cs) main'
        state: present
        filename: spotify
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: Install Vault
      ansible.builtin.package:
        name: vault
