---
- name: Run Apps Role
  ansible.builtin.include_tasks:
    file: ../../shared/tasks/main.yml

# - name: Run Apps Role
#   ansible.builtin.include_tasks:
#     file: install-virtualbox.yml

- name: Run Apps Role
  ansible.builtin.include_tasks:
    file: install-pass.yml

- name: Run Apps Role
  ansible.builtin.include_tasks:
    file: install-solaar.yml

- name: Run Apps Role
  ansible.builtin.include_tasks:
    file: install-slack.yml

- name: Run Install Intellij Role
  ansible.builtin.include_tasks:
    file: install-intellij.yml

- name: Run Apps Role
  ansible.builtin.include_tasks:
    file: install-streamdeck.yml
