- name: Run Apps Role
  ansible.builtin.include_tasks: '{{ item }}'
  loop:
    # - install-virtualbox.yml
    - install-pass.yml
    - install-spotify.yml
    - install-solaar.yml
    # - install-slack.yml
    - install-obs-studio.yml
    - install-streamdeck.yml
