- block:
  - name: Install Homebrew Apps
    community.general.homebrew:
      name: 
        - bash
        - bat
        - exa
        - fd
        - firefox
        - git
        - htop
        - neofetch
        - neovim
        - tldr
        - vim
    when: ansible_distribution == "MacOSX"

  - name: Install Neovim
    community.general.homebrew:
      name: neovim
      install_options: --HEAD
    when: ansible_distribution == "MacOSX"

  - name: Install Docker
    community.general.homebrew:
      name: homebrew/cask/docker
    when: ansible_distribution == "MacOSX"


