- block:
  - name: Install neovim build dependencies
    community.general.homebrew:
      name: 
        - ninja-build
        - gettext
        - libtool
        - autoconf
        - automake
        - cmake
        - unzip
        - curl
        - patch
        - gcc
        - gcc-c++
        - make
        - pkgconfig 
    become: true
    when: ansible_distribution == "MacOSX"

  - name: Clone neovim from github
    ansible.builtin.git:
      repo: https://www.github.com/neovim/neovim.git
      dest: $HOME/src/github/system-repos/neovim
      version: release-0.7
      clone: yes
      update: yes

  - name: Run neovim - make
    ansible.builtin.command: make CMAKE_BUILD_TYPE=Release
    args:
      chdir: $HOME/src/github/system-repos/neovim

  - name: Run neovim - make install
    ansible.builtin.command: make install
    args:
      chdir: $HOME/src/github/system-repos/neovim
    become: true
  tags:
  - apps
