- name: Run Mac Role
  ansible.builtin.include_tasks: '{{ item }}'
  loop:
    - install-base-tools.yml
    # - install-homebrew.yml
    - configure-settings-menu.yml
    - configure-settings-textedit.yml
    - configure-settings-dock.yml
    - configure-settings-finder.yml
