- name: Set NTP Server
  become: true
  tags:
    - system
  block:
    - name: Set NTP to use the local NTP server
      ansible.builtin.copy:
        src: ../templates/timesyncd.conf.j2
        dest: /etc/systemd/timesyncd.conf
        owner: root
        group: root
        mode: '0644'
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: Update apt repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: Install timesyncd (Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        state: present
        name: systemd-timesyncd
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: Restart NTP service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: systemd-timesyncd.service
      when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")

    - name: Install timesyncd (Fedora)
      ansible.builtin.dnf:
        update_cache: true
        state: present
        name: chrony
      when: ansible_distribution == "Fedora"
