---
- name: Disable Cloud Init
  become: true
  tags:
    - system
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Create /etc/cloud
      ansible.builtin.file:
        path: /etc/cloud
        state: directory
        mode: "0755"

    - name: Disable Cloud Init
      ansible.builtin.file:
        path: /etc/cloud/cloud-init.disabled
        state: touch
        mode: "0644"
      tags: molecule-idempotence-notest
