---
dependency:
  name: galaxy
  #options:
  #  role-file: requirements.yml
  #  requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: Ubuntu
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
