- name: Install dev headers
  become: true
  tags:
    - dev
  block:
    - name: Install dev headers (Ubuntu)
      ansible.builtin.apt:
        name:
          - libssl-dev
          - libxml2-utils
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install dev headers (Fedora)
      ansible.builtin.package:
        name:
          - openssl-devel
          - libxml2-devel
      when: ansible_distribution == "Fedora"
