- name: Install java-11-openjdk-devel
  become: true
  tags:
    - dev
  block:
    - name: Install OpenJDK-11 (Ubuntu)
      ansible.builtin.package:
        name:
          - openjdk-11-jdk
      when: ansible_distribution == "Ubuntu"

    - name: Install OpenJDK-11 (Fedora)
      ansible.builtin.package:
        name:
          - java-11-openjdk-devel.x86_64
      when: ansible_distribution == "Fedora"
