- name: Install java-11-openjdk-devel
  become: true
  tags:
    - dev
  block:
    # - name: Install OpenJDK-11 (Ubuntu)

    - name: Download Installer SDKMAN
      ansible.builtin.get_url:
        url: https://get.sdkman.io/?rcupdate=false
        dest: '/tmp/sdkman.sh'
        mode: '750'

    - name: Run SDKMAN Installer
      ansible.builtin.command: '/tmp/sdkman.sh'

    - name: Install Java Temurin 11
      ansible.builtin.command: sdk install java $(sdk list java | grep "11.*-tem" | awk '{print $(NF)}')
