- name: Install Scala and Metals
  vars:
    coursier_dir: '{{ vault_home }}/.local/share/coursier/bin'
  block:
    - name: Download Coursier
      ansible.builtin.get_url:
        url: https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz
        dest: /tmp/cs-x86_64-pc-linux.gz
        mode: '0644'

    - name: Extract Coursier
      ansible.builtin.command:
        cmd: gzip -d cs-x86_64-pc-linux.gz
        chdir: /tmp

    - name: Make Coursier Executable
      ansible.builtin.copy:
        src: /tmp/cs-x86_64-pc-linux
        dest: /tmp/cs
        mode: +x
        remote_src: true

    - name: Install Scala
      ansible.builtin.command:
        cmd: /tmp/cs setup --yes --install-dir {{ coursier_dir }}

    - name: Install Metals
      ansible.builtin.command:
        cmd: '{{ coursier_dir }}/cs install metals'
