- name: Install java-11-openjdk-devel
  tags:
    - dev
  vars:
    sdkman_installer: '/tmp/sdkman.sh'
    sdkman_dir: '{{ vault_home }}/.sdkman'
    sdkman_init: '{{ sdkman_dir }}/bin/sdkman-init.sh'
  block:
    - name: Install Dependencies
      ansible.builtin.package:
        name:
          - curl
          - unzip
          - zip
      become: true

    - name: Download Installer SDKMAN
      ansible.builtin.get_url:
        url: https://get.sdkman.io/?rcupdate=false
        dest: '{{ sdkman_installer }}'
        mode: '750'

    - name: Run SDKMAN Installer
      ansible.builtin.command: '/bin/bash {{ sdkman_installer }}'
      environment:
        SDKMAN_DIR: '{{ sdkman_dir }}'

    - name: Install Java Temurin 11
      ansible.builtin.shell: |
        set -o pipefail
        java_version=$(source {{ sdkman_init }} && sdk list java | grep "11.*-tem" | awk '{print $(NF)} | head --lines 1')
        source {{ sdkman_init }} && sdk install java ${java_version}
      environment:
        SDKMAN_DIR: '{{ sdkman_dir }}'
      args:
        executable: /bin/bash
