- name: Install Scala and Metals
  block:
    - name: Download Coursier
      ansible.builtin.get_url:
        url: https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz
        dest: /tmp/cs-x86_64-pc-linux.gz
        mode: '0644'

    - name: Extract Coursier
      ansible.builtin.shell:
        cmd: gzip -d cs-x86_64-pc-linux.gz
        chdir: /tmp

    - name: Make Coursier Executable
      ansible.builtin.copy:
        src: /tmp/cs-x86_64-pc-linux
        dest: /tmp/cs
        mode: +x
        remote_src: true

    - name: Install Scala
      ansible.builtin.shell:
        cmd: ./cs setup --yes
        chdir: /tmp

    - name: Delete Coursier Download
      ansible.builtin.file:
        path: /tmp/cs-x86_64-pc-linux
        state: absent

    - name: Delete Coursier Download
      ansible.builtin.file:
        path: /tmp/cs
        state: absent

    - name: Install Metals
      ansible.builtin.shell:
        cmd: ./cs install metals
        chdir: "{{ lookup('env', 'HOME') }}/.local/share/coursier/bin"
