- name: Install dotnet
  become: true
  tags:
    - dev
  block:
    - name: Install Microsoft Signing Key
      ansible.builtin.apt:
        deb: https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb
      when: ansible_distribution == "Ubuntu"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install dotnet 6
      ansible.builtin.package:
        name: dotnet-sdk-6.0
      when: ansible_distribution == "Ubuntu"
