- name: Install java-11-openjdk-devel
  become: true
  tags:
    - dev
  block:
    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - curl
          - unzip
          - zip
        update_cache: true

    - name: Download Installer SDKMAN
      ansible.builtin.get_url:
        url: https://get.sdkman.io/?rcupdate=false
        dest: '/tmp/sdkman.sh'
        mode: '750'

    - name: Run SDKMAN Installer
      ansible.builtin.command: '/tmp/sdkman.sh'

    # . {{ lookup('env', 'HOME') }}/.sdkman/bin/sdkman-init.sh
    - name: Install Java Temurin 11
      ansible.builtin.shell: |
        set -o pipefail
        . {{ lookup('env', 'HOME') }}/.sdkman/bin/sdkman-init.sh
        sdk install java $(sdk list java | grep "11.*-tem" | awk '{print $(NF)}')
      args:
        executable: /bin/bash
