- name: Run SDK Role
  ansible.builtin.include_tasks: '{{ item }}'
  loop:
    - install-dev-headers.yml
    - install-dotnet.yml
    - install-java.yml
    - install-nodejs.yml
    - install-npm-packages.yml
    - install-rust.yml
    - install-cargo-packages.yml
