---
- name: Install Rust
  become: true
  become_user: "{{ vault_username }}"
  block:
    - name: Download Installer Rustup
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: ~/rustup.sh
        mode: "0775"
        force: true
        validate_certs: false

    - name: Run Installer Rustup
      ansible.builtin.shell:
        cmd: ~/rustup.sh -y
        creates: "{{ vault_home }}/.cargo/bin/cargo"

    - name: Cleanup
      ansible.builtin.file:
        path: ~/rustup.sh
        state: absent
