---
- name: Install Rust
  become: true
  become_user: "{{ vault_username }}"
  block:
    - name: Download Installer Rustup
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: "775"
        validate_certs: false

    - name: Run Installer Rustup
      ansible.builtin.command:
        cmd: ./rustup.sh -y
        chdir: /tmp
        creates: "{{ vault_home }}/.cargo/bin/cargo"
