---
- name: Converge
  hosts: all
  vars_files: ../../vars/vault.test.yml
  pre_tasks:
    - name: Role - add user
      include_role:
        name: ../../roles/add_users
  tasks:
    - name: Role - hello_world
      include_role:
        name: ../../roles/hello_world
