---
- name: Install OBS Studio
  become: true
  tags:
    - apps
  vars:
    applications_ubuntu_key: /etc/apt/keyrings/obsstudio.asc
    applications_obs_ppa: https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Install OBS Studio dependencies
      ansible.builtin.package:
        name:
          - ffmpeg
          - v4l2loopback-dkms

    - name: Download OBS Studio GPG Key
      ansible.builtin.get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xbc7345f522079769f5bbe987efc71127f425e228
        dest: "{{ applications_ubuntu_key }}"
        mode: "0644"

    #- name: Add OBS Studio Repository
    #  ansible.builtin.apt_repository:
    #    repo: deb [arch=amd64 signed-by={{ applications_ubuntu_key }}] {{ applications_obs_ppa }} {{ ansible_distribution_release }} main
    #    state: present
    #    filename: obsstudio

    - name: Install OBS Studio
      ansible.builtin.package:
        name: obs-studio
