- name: Upgrade Server (Ubuntu or Debian)
  become: true
  when: (ansible_distribution == "Ubuntu") or (ansible_distribution == "Debian")
  block:
    - name: Update apt repo and cache (Ubuntu or Debian)
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Upgrade all packages (Ubuntu or Debian)
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

    - name: Check if reboot is needed (Ubuntu or Debian)
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: false

    - name: Reboot if kernel updated (Ubuntu or Debian)
      ansible.builtin.reboot:
        msg: 'Reboot initiated for kernel updates'
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

- name: Upgrade Server (Fedora)
  become: true
  when: ansible_distribution == "Fedora"
  block:
    - name: Update all packages (Fedora)
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: Check if a reboot is required (Fedora)
      tags: notest
      ansible.builtin.command: needs-restarting -r
      register: reboot_required
      ignore_errors: true
      failed_when: false
      changed_when: reboot_required.rc != 0
      notify: Reboot server
