---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${DISTRO:-ubuntu2204}
    image: geerlingguy/docker-${DISTRO:-ubuntu2204}-ansible:latest
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
