- block:
  - name: Install required system packages
    ansible.builtin.package:
      name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg
        - lsb-release

  - name: Add Docker GPG apt Key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker Repository
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      filename: docker

  - name: Update apt and install docker-ce
    ansible.builtin.package: 
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
  become: true
