- block:
  - name: Disable Logon Background Image
    ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\System
      name: DisableLogonBackgroundImage
      data: 1
      type: dword

  - name: Disable Lock Screen
    ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Personalization
      name: NoLockScreen
      data: 1
      type: dword

  become: true    

