---
- name: Install Go
  vars:
    sdks_golang_version: "1.22.2"
    sdks_golang_dir: "{{ vault_home }}/.golang/bin"
  block:
    - name: Download Installer Go
      ansible.builtin.get_url:
        url: https://go.dev/dl/go{{ sdks_golang_version }}.linux-amd64.tar.gz
        dest: /tmp/go-installer.tar.gz
        mode: "750"
        validate_certs: false

    - name: Make go directory
      ansible.builtin.file:
        path: "{{ sdks_golang_dir }}"
        state: directory
        mode: "0750"

    - name: Run Go Installer
      ansible.builtin.command:
        cmd: tar -C {{ sdks_golang_dir }} -xvf ./go-installer.tar.gz
        chdir: /tmp
        creates: "{{ sdks_golang_dir }}/go"
