- name: Install Polybar
  become: true
  tags:
    - desktop
  block:
    - name: Install polybar build dependencies (Ubuntu)
      ansible.builtin.package:
        name:
          - build-essential
          - git
          - cmake
          - cmake-data
          - pkg-config
          - python3
          - python3-sphinx
          - python3-packaging
      when: ansible_distribution == "Ubuntu"

    - name: Install polybar build dependencies (Fedora)
      ansible.builtin.package:
        name:
          - gcc-c++
          - clang
          - git
          - cmake
          - '@development-tools'
          - python3-sphinx
          - python3-packaging
      when: ansible_distribution == "Fedora"

    - name: Install polybar required dependencies (Ubuntu)
      ansible.builtin.package:
        name:
          - libuv1-dev
          - libcairo2-dev
          - libxcb1-dev
          - libxcb-util0-dev
          - libxcb-randr0-dev
          - libxcb-composite0-dev
          - python3-xcbgen
          - xcb-proto
          - libxcb-image0-dev
          - libxcb-ewmh-dev
          - libxcb-icccm4-dev
      when: ansible_distribution == "Ubuntu"

    - name: Install polybar required dependencies (Fedora)
      ansible.builtin.package:
        name:
          - cairo-devel
          - libuv-devel
          - xcb-util-devel
          - libxcb-devel
          - xcb-proto
          - xcb-util-image-devel
          - xcb-util-wm-devel
      when: ansible_distribution == "Fedora"

    - name: Install polybar optional dependencies (Ubuntu)
      ansible.builtin.package:
        name:
          - libxcb-xkb-dev
          - libxcb-xrm-dev
          - libxcb-cursor-dev
          - libasound2-dev
          - libpulse-dev
          - i3-wm
          - libjsoncpp-dev
          - libmpdclient-dev
          - libcurl4-openssl-dev
          - libnl-genl-3-dev
      when: ansible_distribution == "Ubuntu"

    - name: Install polybar optional dependencies (Fedora)
      ansible.builtin.package:
        name:
          - xcb-util-xrm-devel
          - xcb-util-cursor-devel
          - alsa-lib-devel
          - pulseaudio-libs-devel
          - i3
          - jsoncpp-devel
          - libmpdclient-devel
          - libcurl-devel
          - wireless-tools-devel
          - libnl3-devel
      when: ansible_distribution == "Fedora"

- name: Clone Polybar Repository
  tags:
    - desktop
  block:
    - name: Clone Polybar Repository
      ansible.builtin.git:
        repo: https://github.com/polybar/polybar.git
        dest: $HOME/src/github/system-repos/polybar
        recursive: true

    - name: Make polybar build directory
      ansible.builtin.file:
        path: $HOME/src/github/system-repos/polybar/build
        state: directory
        mode: '0755'

    - name: Run polybar - cmake
      ansible.builtin.command: cmake ..
      args:
        chdir: $HOME/src/github/system-repos/polybar/build

    - name: Run polybar - make
      ansible.builtin.shell: make -j$(nproc)
      args:
        chdir: $HOME/src/github/system-repos/polybar/build

- name: Run polybar Install
  become: true
  tags:
    - desktop
  block:
    - name: Run polybar - make install
      ansible.builtin.command: make install
      args:
        chdir: "{{ lookup('env', 'HOME') }}/src/github/system-repos/polybar/build"
