- name: Run Desktop Role
  include_tasks: "{{ item }}"
  loop:
    - install-xorg.yml
    - install-i3.yml
    - load-dotfiles.yml
    - install-sddm.yml
    - install-polybar.yml
    - install-i3-apps.yml
    - install-dunst.yml
    - install-rofi.yml
    - install-solaar.yml
    - install-polybar-apps.yml
    - install-xmenu.yml
    - install-themes-qt.yml
    - install-themes-gtk.yml
    - symlink-theme-folders.yml
