- name: Make Theme Folders
  tags:
    - desktop
  vars:
    home: '{{ lookup("env", "HOME") }}'
    themes_dir: '{{ home }}/.themes'
    fonts_dir: '{{ home }}/.fonts'
    icons_dir: '{{ home }}/.icons'
  block:
    - name: Make .themes directory
      ansible.builtin.file:
        path: '{{ themes_dir }}'
        state: directory
        mode: '0755'

    - name: Make .fonts directory
      ansible.builtin.file:
        path: '{{ fonts_dir }}'
        state: directory
        mode: '0755'

    - name: Make .icons directory
      ansible.builtin.file:
        path: '{{ icons_dir }}'
        state: directory
        mode: '0755'

- name: Symlink Theme Folders
  become: true
  tags:
    - desktop
  block:
    - name: Link .themes to root
      ansible.builtin.file:
        src: '{{ themes_dir }}'
        dest: /root/.themes
        state: link

    - name: Link .fonts to root
      ansible.builtin.file:
        src: '{{ fonts_dir }}'
        dest: /root/.fonts
        state: link

    - name: Link .icons to root
      ansible.builtin.file:
        src: '{{ icons_dir }}'
        dest: /root/.icons
        state: link
