- name: Install docker
  become: true
  tags:
    - dev
    - container
  block:
    - name: Install required system packages (Ubuntu)
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      when: ansible_distribution == "Ubuntu"

    - name: Install required system packages (Fedora)
      ansible.builtin.package:
        name:
          - ca-certificates
          - curl
      when: ansible_distribution == "Fedora"

    - name: Download Docker GPG Key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.gpg
      when: ansible_distribution == "Ubuntu"

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Update apt and install docker-ce
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
      when: ansible_distribution == "Ubuntu"
