---
- name: Install Linux Desktop - i3wm
  hosts: new
  become_user: root
  vars_files:
    - ../vars/vault.yml
  roles:
    - base_os
    - hestia
    - base_desktop
    - desktop_i3wm
    - sdk_dotnet
    - sdk_rust
    - sdks
    - applications
    - neovim
    - docker
    - docker_rootless
