---
- name: Install Linux Desktop - i3wm
  hosts: new
  become_user: root
  vars_files:
    - ../vars/vault.yml
  roles:
    - add_users
    - shared
    - base_os
    - base_desktop
    - dotfiles
    - neovim
    - desktop_xorg
    - desktop_i3wm
    - desktop_sddm
    - desktop_polybar
    - desktop_dunst
    - desktop_rofi
    - desktop_xmenu
    # - symlink-theme-folders
    # - sdk_dotnet
    - sdk_go
    - sdk_rust
    - sdk_java
    - sdk_nodejs
    - sdk_scala
    - applications
    - app_spotify
    - app_firefox
    - app_obsstudio
    - docker
    - docker_rootless
    - nfs_common

    - hestia
