---
- hosts: new
  name: Install Linux Desktop - i3wm
  become_user: root
  roles:
    - base_os
    - hestia
    - base_desktop
    - desktop_i3wm
    - sdks
    - applications
    - neovim
    - docker
    - docker_rootless
