---
- name: Converge
  hosts: all
  vars_files: ../../vars/vault.test.yml
  pre_tasks:
    - name: Role - add user
      include_role:
        name: ../../roles/add_users
  tasks:
    - name: Role - docker
      include_role:
        name: ../../roles/docker

    - name: Role - docker_rootless
      include_role:
        name: ../../roles/docker_rootless
