- name: Add user
  become: true
  vars:
    adduser_username: gwendolyn
    adduser_password: '{{ vault_gwendolyn_password }}'
  block:
    - name: Add my user account
      ansible.builtin.user:
        name: '{{ adduser_username }}'
        createhome: true
        shell: /bin/bash
        groups: sudo

    - name: Set password
      ansible.builtin.shell: /usr/bin/openssl passwd -6 -salt "p3x515" "{{ adduser_password }}" | awk '{print "{{ adduser_username }}:"$1}' | chpasswd -e
