---
- name: Converge
  hosts: all
  vars_files: ../../vars/vault.test.yml
  pre_tasks:
    - name: Role - add user
      include_role:
        name: ../../roles/add-users
  tasks:
    - name: Role - upgrade-server
      include_role:
        name: ../../roles/upgrade-server
